version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running tests...
      - npm test
  build:
    commands:
      - echo Running tests...
      - npm test

      - aws cloudformation package --template-file stack.yaml --s3-bucket aws-training-codepipeline-374117739894-eu-central-1 --output-template-file packaged-template.yaml

artifacts:
  files:
    - '**/*'
